import { useState } from 'react'
import type { MockModel } from '../mock/useMockState'
import { Avatar, Botanical, Empty, GameArt, Heading, Icon, Modal, Tabs, Tag } from '../components/ui'

export function Championship({ model }: { model: MockModel }) {
  const [tab, setTab] = useState('Overview')
  const [modal, setModal] = useState<'join' | 'result' | 'rules' | null>(null)
  const [feedback, setFeedback] = useState('')
  const counted = model.results.filter(result => result.status === 'confirmed')
  const rankings = [{ name: 'Lucía M.', points: 38, games: 8 }, { name: 'Carlos R.', points: 32, games: 7 }, { name: 'Valeria G.', points: 29, games: 7 }, { name: 'You', points: 24, games: 6 }, { name: 'David P.', points: 22, games: 6 }, { name: 'Mariana S.', points: 20, games: 5 }].map(player => {
    const matches = counted.filter(result => result.author === player.name || result.opponent === player.name)
    const points = matches.reduce((sum, result) => {
      const won = result.author === player.name ? result.score > result.opponentScore : result.opponentScore > result.score
      return sum + (won ? 5 : 3)
    }, 0)
    return { name: player.name === 'You' ? model.profile.name : player.name, points: player.points + points, games: player.games + matches.length }
  }).sort((a, b) => b.points - a.points)
  return <><Heading eyebrow="A LITTLE FRIENDLY COMPETITION" title="Play. Connect. Compete.">Different game each month. The same wonderful reason to gather.</Heading><section className="champ-hero"><div><Tag tone="gold">OCTOBER 2026 CHAMPIONSHIP</Tag><h2>All aboard<br/>for good company.</h2><p>Build routes. Explore new cities. Meet your next favorite opponent.</p><div className="champ-game">Ticket to Ride <span>October 1 – 24</span></div><button className="button light" onClick={() => model.registered ? setModal('result') : setModal('join')}>{model.registered ? 'Submit a match result' : 'Join the Championship'}<Icon name="arrow" size={18}/></button><small>{model.registered ? 'You’re registered. Let the friendly competition begin.' : model.member ? 'Included with your membership' : 'L200 competition-only entry · preview price'}</small></div><GameArt type="rail"/><Botanical/></section>
    <div className="stat-strip"><div><strong>32</strong><span>players, and counting</span></div><div><strong>48</strong><span>games played together</span></div><div><strong>6</strong><span>seats at The Final Table</span></div><div><strong>Oct 25</strong><span>one memorable finale</span></div></div>
    <Tabs items={['Overview', 'Leaderboard', 'My Matches', 'The Final Table', 'Past Champions']} value={tab} onChange={setTab}/>
    {tab === 'Overview' && <div className="two-column"><section className="panel"><div className="section-heading"><h2>A month of possibility</h2><Icon name="trophy"/></div>{[['Join the championship', 'Your membership includes entry. Nonmembers are welcome with a competition ticket.'], ['Play wherever you gather', 'Arrange qualifying games with other registered players — at a café, a home, or a community table.'], ['Record, confirm, cheer each other on', 'Submit your result and have another player confirm it. Only confirmed games count.'], ['A seat at The Final Table', 'Our top six players gather on October 25 for a friendly in-person final.']].map(([title, body], i) => <div className="step" key={title}><span>{i + 1}</span><div><h3>{title}</h3><p>{body}</p></div></div>)}<button className="text-button" onClick={() => setModal('rules')}>Read the October rules <Icon name="arrow" size={17}/></button></section><aside className="panel warm"><span className="eyebrow">THE SPIRIT OF OUR CHAMPIONSHIP</span><h2>For the love<br/>of the game.</h2><p>You don’t have to be the best player in the room. Just bring your curiosity, be a good sport, and enjoy the people across the table.</p><Botanical/><div className="notice"><Icon name="star"/> Bragging rights. A little prize. A lot of belonging.</div></aside></div>}
    {tab === 'Leaderboard' && <section className="panel"><div className="section-heading"><div><span className="eyebrow">OCTOBER · TICKET TO RIDE</span><h2>A little friendly rivalry</h2></div><Tag>Confirmed results only</Tag></div><div className="table-scroll"><table className="leaderboard"><thead><tr><th>Rank</th><th>Player</th><th>Games</th><th>Points</th></tr></thead><tbody>{rankings.map((row, i) => <tr key={row.name} className={row.name === model.profile.name ? 'you-row' : ''}><td><span className={`rank rank-${i}`}>{i < 3 ? <Icon name="trophy" size={20}/> : String(i + 1).padStart(2, '0')}</span></td><td><div className="host"><Avatar name={row.name}/><strong>{row.name}</strong>{row.name === model.profile.name && <Tag>You</Tag>}</div></td><td>{row.games}</td><td><strong>{row.points}</strong></td></tr>)}</tbody></table></div><p className="meta">Preview scoring: first place 5 points, second 3. Ties are held for review. The first six qualify; final selection closes October 24.</p></section>}
    {tab === 'My Matches' && <section className="panel"><div className="section-heading"><h2>Your games, together</h2><button className="button" onClick={() => setModal(model.registered ? 'result' : 'join')}>{model.registered ? 'Submit Result' : 'Register to play'}<Icon name="plus" size={17}/></button></div>{!model.registered ? <Empty title="Your first match is waiting">Join this month’s championship to submit results and confirm games.</Empty> : model.results.map(result => <div className="result-card" key={result.id}><div><Tag tone={result.status === 'confirmed' ? '' : 'peach'}>{result.status === 'pending' ? 'Awaiting confirmation' : result.status}</Tag><h3>{result.author === 'You' ? model.profile.name : result.author} & {result.opponent === 'You' ? model.profile.name : result.opponent}</h3><p>{result.date} · Score {result.score} — {result.opponentScore}</p></div><div className="actions">{result.status === 'pending' && (result.author !== 'You' ? <><button className="button small" onClick={() => { model.setResults(previous => previous.map(r => r.id === result.id ? { ...r, status: 'confirmed' } : r)); setFeedback('Result confirmed. The leaderboard has been updated.') }}>Confirm</button><button className="button secondary small" onClick={() => { model.setResults(previous => previous.map(r => r.id === result.id ? { ...r, status: 'disputed' } : r)); setFeedback('Result flagged for review. It will not count toward the leaderboard.') }}>Dispute</button></> : <span className="meta">Waiting for {result.opponent}<br/>You cannot confirm your own result.</span>)}</div></div>)}{feedback && <div role="status" className="notice"><Icon name="check"/>{feedback}</div>}</section>}
    {tab === 'The Final Table' && <div className="two-column"><section className="panel final-panel"><span className="trophy-mark"><Icon name="trophy" size={66}/></span><span className="eyebrow">ONE TABLE. A MONTH OF MEMORIES.</span><h2>The October Final Table</h2><p>Sunday, October 25 · 6:00–10:00 PM</p><p>The Crowded Table · Tegucigalpa</p><div className="tags"><Tag>Ticket to Ride</Tag><Tag tone="gold">Top 6 players</Tag></div><p>One last game, a small surprise for our champion, and a celebration of everyone who pulled up a chair.</p><div className="notice"><Icon name="lock"/> Private address shared with confirmed finalists.</div></section><section className="panel"><h2>The road to the final</h2><p className="muted">These players currently lead the way. Finalists are confirmed after qualifying closes on October 24.</p>{rankings.map((row, i) => <div className="member-row" key={row.name}><span className="meta">0{i + 1}</span><Avatar name={row.name}/><strong>{row.name}</strong><span className="push-right">{row.points} pts</span></div>)}<Tag tone="gold">Provisional · not final qualification</Tag></section></div>}
    {tab === 'Past Champions' && <div className="card-grid">{[{ month: 'September', game: 'Catan', name: 'Ana R.', art: 'forest' as const }, { month: 'August', game: 'Carcassonne', name: 'Daniel M.', art: 'rail' as const }].map(row => <article className="panel champion-card" key={row.month}><GameArt type={row.art}/><Tag tone="gold"><Icon name="trophy" size={14}/> {row.month} 2026</Tag><h2>{row.name}</h2><p>{row.game} champion</p><span className="meta">A permanent place in our table’s story.</span></article>)}</div>}
    {modal === 'join' && <Modal title="Your next adventure starts here" onClose={() => setModal(null)}><GameArt type="rail" className="small-art"/><h3>October Championship · Ticket to Ride</h3><p>{model.member ? 'Your entry is included with membership.' : 'L200 gives you access to this championship. Meet & Play and Community remain members-only.'}</p><div className="notice"><Icon name="trophy"/> Qualify October 1–24 · Final October 25</div><p className="meta">{!model.member && 'Preview payment only; no charge will be made. '}All players agree to friendly play, honest results, and independent match confirmation.</p><button className="button full" onClick={() => { model.setRegistered(true); model.notify('You’re in! Welcome to the October Championship.'); setModal(null) }}>{model.member ? 'Count me in' : 'Simulate entry payment'}<Icon name="check" size={18}/></button></Modal>}
    {modal === 'result' && <Modal title="Record a good game" onClose={() => setModal(null)}><p className="muted">Another participant will confirm your result before it counts. This preview models a two-player match.</p><form className="form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const score = Number(f.get('score')); const opponentScore = Number(f.get('opponentScore')); model.setResults(previous => [...previous, { id: crypto.randomUUID(), author: 'You', opponent: String(f.get('opponent')), score, opponentScore, date: String(f.get('date')), status: score === opponentScore ? 'disputed' : 'pending' }]); setModal(null); setTab('My Matches'); setFeedback(score === opponentScore ? 'Tied result sent for review. It is not included in standings.' : 'Your result was sent to your opponent for confirmation.') }}><label>Played with<select name="opponent"><option>Lucía M.</option><option>Carlos R.</option><option>Valeria G.</option></select></label><label>Date played<input name="date" type="date" min="2026-10-01" max="2026-10-24" defaultValue="2026-10-04" required/></label><div className="form-row"><label>Your score<input name="score" type="number" min="0" max="300" required/></label><label>Opponent’s score<input name="opponentScore" type="number" min="0" max="300" required/></label></div><button className="button" type="submit">Send for confirmation <Icon name="arrow" size={18}/></button></form></Modal>}
    {modal === 'rules' && <Modal title="October · How we play" onClose={() => setModal(null)}><ol className="rules"><li>Register before playing a qualifying game.</li><li>Play the standard Ticket to Ride base game with another registered player.</li><li>For this preview, a two-player win earns 5 points; second place earns 3. Tied scores go to review.</li><li>Another participant must confirm the submitted result. Pending and disputed results do not count.</li><li>Qualifying closes October 24. The top six meet on October 25.</li><li>Be kind, explain the rules, and put people before points.</li></ol><p className="meta">Illustrative October rules. Final scoring and tie-break policy will be agreed before launch.</p></Modal>}
  </>
}
