import { useState } from 'react'
import type { MockModel } from '../mock/useMockState'
import { members, topics } from '../mock/data'
import { Avatar, Botanical, Empty, GameArt, Heading, Icon, Modal, Tabs, Tag } from '../components/ui'

export function Community({ model }: { model: MockModel }) {
  const [tab, setTab] = useState('Discussions')
  const [topic, setTopic] = useState('All discussions')
  const [search, setSearch] = useState('')
  const [modal, setModal] = useState<string | null>(null)
  const [reply, setReply] = useState('')
  const saved = model.savedGames
  const setSaved = model.setSavedGames
  const [spot, setSpot] = useState('All spots')
  const post = model.posts.find(p => p.id === modal)
  const person = members.find(m => m.name === modal)
  const filtered = model.posts.filter(p => (topic === 'All discussions' || p.topic === topic) && `${p.title} ${p.body}`.toLowerCase().includes(search.toLowerCase()))
  const places = [{ name: 'Café Paradiso', type: 'Cafés', area: 'Col. Palmira', text: 'Good coffee. Big tables. A lovely spot for a casual game.', art: 'birds' as const }, { name: 'The Dice Corner', type: 'Stores', area: 'Central Tegucigalpa', text: 'A welcoming place to find a new game and fellow players.', art: 'rpg' as const }, { name: 'Parque La Leona', type: 'Play spaces', area: 'La Leona', text: 'Fresh air, city views, and room for a sunny afternoon.', art: 'forest' as const }]
  return <><Heading eyebrow="PEOPLE MAKE THE BEST GAMES" title="A place to belong." action={<button className="button" onClick={() => setModal('new')}><Icon name="plus" size={18}/> Start a conversation</button>}>Same table. More friends. Make yourself at home.</Heading><div className="community-hero"><div><span className="eyebrow">YOUR LITTLE CORNER OF TEGUCIGALPA</span><h2>Come for a game.<br/>Stay for the people.</h2></div><p>Ask a question. Share a favorite.<br/>Say hello to someone new.<br/><strong>There’s a whole community around you.</strong></p><Botanical/></div><Tabs items={['Discussions', 'Members', 'Game Recommendations', 'Local Spots']} value={tab} onChange={value => { setTab(value); setSearch('') }}/>
    {tab === 'Discussions' && <div className="discussion-layout"><aside className="topic-panel"><span className="eyebrow">AROUND THE COMMUNITY</span>{topics.map((t, i) => <button key={t} className={topic === t ? 'selected' : ''} onClick={() => setTopic(t)}><Icon name={['chat', 'people', 'dice', 'calendar', 'star', 'leaf', 'heart'][i]} size={18}/>{t}<span>{t === 'All discussions' ? model.posts.length : model.posts.filter(p => p.topic === t).length}</span></button>)}<div className="guideline"><Icon name="heart"/><h3>A kinder kind of community</h3><p>Welcome every experience level. Listen with curiosity. Keep people at the heart of play.</p><button className="text-button" onClick={() => setModal('guidelines')}>Our table manners <Icon name="arrow" size={15}/></button></div></aside><section><label className="search"><Icon name="search"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Find a conversation…" aria-label="Search discussions"/></label><div className="post-list">{filtered.map(p => <button className="post-card" key={p.id} onClick={() => { setReply(''); setModal(p.id) }}><div className="host"><Avatar name={p.author}/><div><strong>{p.author}</strong><small>Community member</small></div><Tag>{p.topic}</Tag></div><h3>{p.title}</h3><p>{p.body}</p><div className="post-footer"><span><Icon name="chat" size={16}/> {p.replies.length} {p.replies.length === 1 ? 'reply' : 'replies'}</span><span>Join the conversation <Icon name="arrow" size={16}/></span></div></button>)}</div>{!filtered.length && <Empty title="Be the first to pull up a chair">Start a conversation in this topic, or try another search.</Empty>}</section></div>}
    {tab === 'Members' && <><div className="filter-bar"><label className="search"><Icon name="search"/><input aria-label="Search members" value={search} onChange={e => setSearch(e.target.value)} placeholder="Find people by name or interest…"/></label><Tag><Icon name="lock" size={14}/> Visible to members only</Tag></div><div className="card-grid">{members.filter(m => `${m.name} ${m.interests.join(' ')}`.toLowerCase().includes(search.toLowerCase())).map(m => <button className="panel member-card" key={m.name} onClick={() => setModal(m.name)}><Avatar name={m.name} large tone={m.color}/><h3>{m.name}</h3><p className="meta"><Icon name="pin" size={14}/> Tegucigalpa</p><p>{m.bio}</p><div className="tags">{m.interests.map(t => <Tag key={t}>{t}</Tag>)}</div><span className="text-button">Get to know {m.name.split(' ')[0]} <Icon name="arrow" size={16}/></span></button>)}</div>{!members.some(m => `${m.name} ${m.interests.join(' ')}`.toLowerCase().includes(search.toLowerCase())) && <Empty title="No one found just yet">Try a different name or interest.</Empty>}</>}
    {tab === 'Game Recommendations' && <><div className="section-heading"><h2>A few community favorites</h2><button className="text-button" onClick={() => { setTopic('Game recommendations'); setTab('Discussions') }}>Talk about your favorites <Icon name="arrow" size={17}/></button></div><div className="card-grid">{[{ game: 'Cascadia', art: 'forest' as const, name: 'Lucía M.', text: 'A peaceful little puzzle. Perfect for a quiet afternoon with someone new.', tag: 'Nature & strategy' }, { game: 'Azul', art: 'azul' as const, name: 'Valeria G.', text: 'Beautiful to look at, easy to teach, and so satisfying. My first-night favorite.', tag: 'Beginner friendly' }, { game: 'Wingspan', art: 'birds' as const, name: 'Carlos R.', text: 'Come for the birds. Stay for the clever little engine you build together.', tag: 'Thoughtful strategy' }].map(g => <article className="recommendation" key={g.game}><GameArt type={g.art}/><div><Tag>{g.tag}</Tag><h3>{g.game}</h3><p>“{g.text}”</p><div className="host"><Avatar name={g.name}/><span>Recommended by {g.name}</span></div><button className="button secondary full" onClick={() => setSaved(previous => previous.includes(g.game) ? previous.filter(v => v !== g.game) : [...previous, g.game])}><Icon name={saved.includes(g.game) ? 'check' : 'plus'} size={16}/>{saved.includes(g.game) ? 'On your play list' : 'Add to my play list'}</button></div></article>)}</div></>}
    {tab === 'Local Spots' && <><div className="section-heading"><div><h2>A few places to gather</h2><p className="meta">Illustrative community suggestions · confirm venue details before visiting.</p></div><select aria-label="Filter local spots" value={spot} onChange={e => setSpot(e.target.value)}>{['All spots', 'Cafés', 'Stores', 'Play spaces'].map(s => <option key={s}>{s}</option>)}</select></div><div className="local-map"><div className="map-road one"/><div className="map-road two"/><div className="map-road three"/><span className="map-area">TEGUCIGALPA</span>{places.map((p, i) => <button key={p.name} style={{ left: `${22 + i * 26}%`, top: `${35 + i % 2 * 25}%` }} onClick={() => setModal(p.name)}><Icon name="pin" size={22}/><span>{p.name}</span></button>)}</div><div className="card-grid">{places.filter(p => spot === 'All spots' || p.type === spot).map(p => <button className="panel place-card" key={p.name} onClick={() => setModal(p.name)}><GameArt type={p.art}/><Tag>{p.type}</Tag><h3>{p.name}</h3><p>{p.text}</p><span className="meta">{p.area} <Icon name="arrow" size={16}/></span></button>)}</div></>}
    {modal === 'new' && <Modal title="Start a good conversation" onClose={() => setModal(null)}><form className="form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const title = String(f.get('title')).trim(); const body = String(f.get('body')).trim(); if (!title || !body) return; const newTopic = String(f.get('topic')); model.setPosts(previous => [{ id: crypto.randomUUID(), author: model.profile.name, title, body, topic: newTopic, replies: [] }, ...previous]); setModal(null); setTab('Discussions'); setTopic('All discussions'); setSearch(''); model.notify('Your conversation is on the community board.') }}><label>Topic<select name="topic" defaultValue={topic === 'All discussions' ? 'General' : topic}>{topics.slice(1).map(t => <option key={t}>{t}</option>)}</select></label><label>A little headline<input name="title" required maxLength={100} placeholder="What’s on your mind?"/></label><label>Pull up a chair<textarea name="body" required maxLength={2000} placeholder="A question, a recommendation, a little hello…"/></label><button className="button" type="submit">Share with the community <Icon name="arrow" size={17}/></button></form></Modal>}
    {post && <Modal title="Around the community board" onClose={() => setModal(null)}><Tag>{post.topic}</Tag><h2 className="detail-title">{post.title}</h2><div className="host"><Avatar name={post.author}/><strong>{post.author}</strong></div><p className="description">{post.body}</p><h3>{post.replies.length} replies</h3>{post.replies.map((r, i) => <div className="chat-message" key={i}><Avatar name={r.author}/><div><strong>{r.author}</strong><p>{r.body}</p></div></div>)}<form className="form" onSubmit={e => { e.preventDefault(); if (!reply.trim()) return; model.setPosts(previous => previous.map(p => p.id === post.id ? { ...p, replies: [...p.replies, { author: model.profile.name, body: reply.trim() }] } : p)); setReply('') }}><label>Join the conversation<textarea required value={reply} onChange={e => setReply(e.target.value)} placeholder="A kind word goes a long way…" maxLength={1000}/></label><button className="button" type="submit">Post reply <Icon name="arrow" size={17}/></button></form></Modal>}
    {person && <Modal title="Someone around your table" onClose={() => setModal(null)}><div className="member-preview"><Avatar name={person.name} large tone={person.color}/><h2>{person.name}</h2><p>Tegucigalpa · Member since September 2026</p><p className="description">{person.bio}</p><div className="tags">{person.interests.map(t => <Tag key={t}>{t}</Tag>)}</div><div className="notice"><Icon name="people"/> Get to know each other at a shared table. Conversations happen in your confirmed table’s chat.</div></div></Modal>}
    {modal === 'guidelines' && <Modal title="Good people. Good table manners." onClose={() => setModal(null)}><ol className="rules"><li>Welcome new people and every experience level.</li><li>Be kind, respectful, and curious. No harassment or exclusion.</li><li>Respect privacy. Don’t share someone’s address or personal information.</li><li>Keep your commitments; release seats when plans change.</li><li>Help each other learn. A shared laugh is worth more than a win.</li></ol></Modal>}
    {places.some(p => p.name === modal) && <Modal title={modal!} onClose={() => setModal(null)}><GameArt type={places.find(p => p.name === modal)!.art} className="small-art"/><p>{places.find(p => p.name === modal)!.text}</p><p className="muted">{places.find(p => p.name === modal)!.area}</p><div className="notice"><Icon name="pin"/> This is a sample place for exploring the design, not a verified venue listing.</div></Modal>}
  </>
}
