import { useState } from 'react'
import type { MockModel } from '../mock/useMockState'
import type { Activity } from '../mock/data'
import { ActivityCard } from '../components/Activity'
import { Botanical, Empty, Heading, Icon, Modal, Tabs } from '../components/ui'

export function MeetPlay({ model, open }: { model: MockModel; open: (id: string) => void }) {
  const [tab, setTab] = useState('Find a Table')
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState('All games')
  const [location, setLocation] = useState('Anywhere')
  const [beginner, setBeginner] = useState(false)
  const [modal, setModal] = useState<'create' | 'match' | null>(null)
  const items = model.items.filter(row => row.kind === 'table' && (tab === 'Find a Table' || row.host === 'You' || model.seats[row.id]) && `${row.title} ${row.host} ${row.location}`.toLowerCase().includes(search.toLowerCase()) && (category === 'All games' || row.category === category) && (location === 'Anywhere' || (location === 'Public places' ? !row.private : row.private)) && (!beginner || row.tags.includes('Beginner friendly')))
  return <><Heading eyebrow="DIFFERENT GAMES. SAME TABLE." title="Meet & Play" action={<button className="button" onClick={() => setModal('create')}><Icon name="plus" size={18}/> Create a Table</button>}>You bring the games. We’ll help you find the people.</Heading><section className="meet-banner"><div><span className="eyebrow">GOOD PEOPLE FIND GREAT GAMES HERE</span><h2>Your next favorite group<br/>starts with a hello.</h2><p>Homes, cafés, a sunny afternoon. There’s more than one way to gather.</p></div><div className="match-callout"><span className="round-icon"><Icon name="people" size={26}/></span><h3>Meet someone new</h3><p>A familiar game. A few unfamiliar faces.<br/>Let us help you find your next table.</p><button className="button light" onClick={() => setModal('match')}>{model.matching ? 'Update your preferences' : 'Find my people'}<Icon name="arrow" size={17}/></button></div><Botanical/></section>
    <div className="section-heading"><Tabs items={['Find a Table', 'My Tables']} value={tab} onChange={setTab}/><span className="meta">Made by members, for members</span></div><div className="filter-bar"><label className="search"><Icon name="search"/><input placeholder="Find a game, host, or place…" aria-label="Search tables" value={search} onChange={e => setSearch(e.target.value)}/></label><select aria-label="Game type" value={category} onChange={e => setCategory(e.target.value)}>{['All games', 'Board Game', 'RPG', 'TCG', 'Social / Party', 'Classic Games', 'Other'].map(t => <option key={t}>{t}</option>)}</select><select aria-label="Location type" value={location} onChange={e => setLocation(e.target.value)}>{['Anywhere', 'Public places', 'Private locations'].map(t => <option key={t}>{t}</option>)}</select><label className="check-label"><input type="checkbox" checked={beginner} onChange={e => setBeginner(e.target.checked)}/> Beginner friendly</label></div>
    {tab === 'My Tables' && <div className="notice"><Icon name="leaf"/> Your hosted tables, reservations, requests, and waitlist spots — all in one place.</div>}
    <div className="card-grid">{items.map(item => <ActivityCard key={item.id} item={item} onOpen={() => open(item.id)} status={model.seats[item.id]}/>)}</div>{!items.length && <Empty title="Let’s make room for something new">Try another filter, or create the table you’d love to join.</Empty>}
    <div className="community-note"><Icon name="heart"/><span>A good table starts with kindness. Welcome new players, respect each other’s time, and leave room for one more.</span></div>
    {modal === 'create' && <Modal title="Make room at your table" onClose={() => setModal(null)}><CreateTable onSave={item => { model.setItems(previous => [item, ...previous]); model.notify('Your table is ready. Let’s find you some company!'); setModal(null); setTab('My Tables'); setSearch(''); setCategory('All games'); setLocation('Anywhere'); setBeginner(false) }}/></Modal>}
    {modal === 'match' && <Modal title="Let’s find your people" onClose={() => setModal(null)}><p className="muted">Tell us a little about your ideal evening. A community host will help connect you with a table.</p><form className="form" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); model.setMatchingPreferences({ availability: String(data.get('availability')), game: String(data.get('game')), style: String(data.get('style')), notes: String(data.get('notes')) }); model.setMatching(true); model.notify('Your matching preferences are with our community hosts. We’ll help you find a table.'); setModal(null) }}><label>When would you like to play?<select name="availability" defaultValue={model.matchingPreferences.availability} required><option>Saturday evening</option><option>Sunday afternoon</option><option>Weekday evenings</option></select></label><label>Your kind of game<select name="game" defaultValue={model.matchingPreferences.game}><option>Strategy games</option><option>Social & party games</option><option>RPGs</option><option>A little bit of everything</option></select></label><label>How do you like to play?<select name="style" defaultValue={model.matchingPreferences.style}><option>Casual — here for good company</option><option>Learning — show me something new</option><option>Competitive — a friendly challenge</option></select></label><label>Anything else?<textarea name="notes" defaultValue={model.matchingPreferences.notes} placeholder="A game you’d love to try, or what makes a great table…" maxLength={500}/></label><button className="button" type="submit">Send my preferences <Icon name="arrow" size={18}/></button></form></Modal>}
  </>
}

function CreateTable({ onSave }: { onSave: (item: Activity) => void }) {
  const [privateLocation, setPrivateLocation] = useState(true)
  const [error, setError] = useState('')
  return <form className="form" onSubmit={e => {
    e.preventDefault(); const f = new FormData(e.currentTarget); const time = String(f.get('time')); const end = String(f.get('end'))
    if (end <= time) { setError('End time must be after start time for this same-day table.'); return }
    const title = String(f.get('title')).trim(); const address = String(f.get('location')).trim()
    if (!title || !address) { setError('Please add a title and meeting location.'); return }
    onSave({ id: crypto.randomUUID(), title, kind: 'table', art: 'forest', category: String(f.get('category')), date: String(f.get('date')), time, end, capacity: Number(f.get('capacity')), filled: 1, host: 'You', private: privateLocation, location: privateLocation ? 'Private location · Tegucigalpa' : address, address: privateLocation ? address : undefined, description: String(f.get('description')).trim(), joinMode: f.get('mode') as 'instant' | 'request', tags: f.get('beginner') ? ['Beginner friendly'] : ['Experienced players'] })
  }}><p className="muted">A favorite game, a little space, and a few new friends.</p><label>What are we playing?<input name="title" placeholder="e.g. Wingspan & Sunday coffee" required maxLength={70}/></label><div className="form-row"><label>Game type<select name="category">{['Board Game', 'RPG', 'TCG', 'Social / Party', 'Classic Games', 'Other'].map(t => <option key={t}>{t}</option>)}</select></label><label>Total seats, including you<input name="capacity" type="number" min="2" max="30" defaultValue="5" required/></label></div><div className="form-row three"><label>Date<input type="date" name="date" defaultValue="2026-10-17" required/></label><label>Starts<input type="time" name="time" defaultValue="16:00" required/></label><label>Ends<input type="time" name="end" defaultValue="19:00" required/></label></div><label className="check-label"><input type="checkbox" checked={privateLocation} onChange={e => setPrivateLocation(e.target.checked)}/> This is a private location</label><label>{privateLocation ? 'Exact meeting address (confirmed guests only)' : 'Public meeting place'}<input name="location" placeholder={privateLocation ? 'Use a fictional address for this preview' : 'Café name and general location'} required maxLength={150}/></label><label>How should people join?<select name="mode"><option value="request">Request a seat — I’ll approve each guest</option><option value="instant">Take a seat — instant confirmation</option></select></label><label>Tell us about your table<textarea name="description" placeholder="What should people expect? Keep private addresses out of this description." required maxLength={1000}/></label><label className="check-label"><input name="beginner" type="checkbox" defaultChecked/> First timers welcome — happy to teach</label>{error && <p role="alert" className="error">{error}</p>}<button type="submit" className="button">Create my table <Icon name="plus" size={18}/></button></form>
}

