import { formatDate, formatTime } from '../mock/format'
import { useState } from 'react'
import type { Activity } from '../mock/data'
import type { MockModel } from '../mock/useMockState'
import { Avatar, GameArt, Icon, Modal, Tag } from './ui'

export function ActivityCard({ item, onOpen, status }: { item: Activity; onOpen: () => void; status?: string }) {
  const left = item.capacity - item.filled
  return <button className="activity-card" onClick={onOpen}>
    <div className="card-art"><GameArt type={item.art}/><span className={`art-label ${item.special ? 'special' : ''}`}>{item.category}</span><span className="date-stamp"><b>{new Date(item.date + 'T12:00:00').getDate()}</b><span>{new Date(item.date + 'T12:00:00').toLocaleDateString('en-US', { month: 'short' }).toUpperCase()}</span></span></div>
    <div className="activity-body"><div className="meta">{formatDate(item.date, true)} <span>·</span> {formatTime(item.time)}</div><h3>{item.title}</h3><p className="location"><Icon name={item.private ? 'lock' : 'pin'} size={14}/>{item.location}</p>{item.kind === 'table' && <div className="host"><Avatar name={item.host}/><span>Hosted by <strong>{item.host}</strong></span></div>}<div className="card-bottom"><span className={left === 0 ? 'muted' : 'availability'}><span className={`dot ${left === 0 ? 'rust' : ''}`}/>{status ? status === 'confirmed' ? 'You’re going' : status === 'requested' ? 'Request sent' : 'On the waitlist' : left ? `${left} seats open` : 'This table is crowded'}</span><Icon name="arrow" size={19}/></div></div>
  </button>
}

export function ActivityDialog({ id, model, onClose }: { id: string; model: MockModel; onClose: () => void }) {
  const [pay, setPay] = useState(false)
  const [message, setMessage] = useState('')
  const item = model.items.find(row => row.id === id)
  if (!item) return null
  const status = model.seats[id]
  const hosting = item.host === 'You'
  const access = hosting || status === 'confirmed'
  const cost = item.special ? item.price : !model.member && item.kind === 'official' ? 125 : 0
  const canChat = model.member && item.kind === 'table' && access
  function reserve() { if (cost && item!.filled < item!.capacity) setPay(true); else model.join(item!) }
  return <Modal title={item.kind === 'official' ? 'Around our table' : 'A table for good company'} onClose={onClose} wide>
    <GameArt type={item.art} className="detail-art"/><div className="detail-grid"><div><div className="eyebrow">{item.category}</div><h2 className="detail-title">{item.title}</h2><div className="host"><Avatar name={item.host}/><span>Hosted by <strong>{item.host}</strong></span></div><p className="description">{item.description}</p><div className="tags">{item.tags.map(tag => <Tag key={tag}>{tag}</Tag>)}</div><h3 className="section-label">A few things to know</h3><p className="muted">Bring your curiosity and a little kindness. If your plans change, please release your seat so someone else can join.</p>
    {hosting && <div className="request-list"><h3>Seat requests</h3>{model.requests.filter(r => r.activity === id).length === 0 && <p className="muted">No requests yet. Your table is ready for company.</p>}{model.requests.filter(r => r.activity === id).map(r => <div className="request" key={r.id}><Avatar name={r.name}/><div><strong>{r.name}</strong><small>{r.status === 'pending' ? 'Would love to join your table' : r.status}</small></div>{r.status === 'pending' && <><button className="button small" disabled={item.filled >= item.capacity} onClick={() => model.decideRequest(r.id, true)}>Accept</button><button className="text-button" onClick={() => model.decideRequest(r.id, false)}>Decline</button></>}</div>)}</div>}
    {canChat && <div className="chat-box"><h3><Icon name="chat"/> Table conversation</h3><p className="meta">Only your confirmed table · available until 48 hours after play</p><div className="chat-message"><Avatar name={item.host}/><div><strong>{item.host}</strong><p>Looking forward to playing together! Feel free to ask about the rules.</p></div></div>{(model.messages[id] || []).map((m, i) => <div className="chat-message" key={i}><Avatar name={m.author}/><div><strong>{m.author}</strong><p>{m.text}</p></div></div>)}<form className="chat-form" onSubmit={e => { e.preventDefault(); if (!message.trim()) return; model.setMessages(previous => ({ ...previous, [id]: [...(previous[id] || []), { author: model.profile.name, text: message.trim() }] })); setMessage('') }}><input aria-label="Message your table" placeholder="Say hello to your table…" value={message} onChange={e => setMessage(e.target.value)} maxLength={1000} required/><button className="button" type="submit">Send <Icon name="arrow" size={16}/></button></form></div>}
    </div><aside className="reservation"><div className="detail-fact"><Icon name="calendar"/><div><strong>{formatDate(item.date)}</strong><span>{new Date(item.date + 'T12:00:00').getFullYear()}</span></div></div><div className="detail-fact"><Icon name="clock"/><div><strong>{formatTime(item.time)} – {formatTime(item.end)}</strong><span>Tegucigalpa time</span></div></div><div className="detail-fact"><Icon name={item.private ? 'lock' : 'pin'}/><div><strong>{item.location}</strong><span>{item.private ? access ? item.address || 'Demo address: 12 Garden Lane (fictional)' : 'Exact address shared after confirmation' : 'Meet us at the main entrance'}</span></div></div><div className="detail-fact"><Icon name="people"/><div><strong>{item.filled} of {item.capacity} seats filled</strong><span>{item.capacity > item.filled ? 'A little room for you' : 'Join the waitlist for the next opening'}</span></div></div><div className="seat-bar"><span style={{ width: `${item.filled / item.capacity * 100}%` }}/></div>
    {hosting ? <div className="notice"><Icon name="check"/> You’re hosting this table</div> : status ? <><div className="notice"><Icon name={status === 'confirmed' ? 'check' : 'clock'}/>{status === 'confirmed' ? 'Your seat is confirmed' : status === 'requested' ? 'Waiting for host approval' : 'You’re on the waitlist'}</div><p className="meta">{status === 'requested' ? 'We’ll let you know when your host responds.' : status === 'waitlisted' ? 'We’ll notify you when a seat opens.' : 'We can’t wait to see you.'}</p><button className="text-button danger" onClick={() => model.cancel(id)}>Cancel {status === 'requested' ? 'request' : status === 'waitlisted' ? 'waitlist spot' : 'reservation'}</button></> : pay ? <div className="demo-checkout"><h3>Your evening awaits</h3><p>One seat · <strong>L{cost}</strong></p><p className="meta">Preview checkout. No payment details are collected or charged.</p><button className="button full" onClick={() => { model.join(item); setPay(false) }}>Simulate payment & reserve</button><button className="text-button" onClick={() => setPay(false)}>Go back</button></div> : <><div className="price">{cost ? `L${cost}` : 'Included'}<small>{cost ? 'per person' : 'with your membership'}</small></div><button className="button full" onClick={reserve}>{item.filled >= item.capacity ? 'Join Waitlist' : cost ? `Reserve for L${cost}` : item.joinMode === 'request' ? 'Request a Seat' : 'Take a Seat'}<Icon name="arrow" size={17}/></button></>}
    <div className="privacy-note"><Icon name="lock" size={15}/><span>Private by design.<br/>Good company by choice.</span></div></aside></div>
  </Modal>
}

